# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env_vars:
  global:
    - RGL_USE_NULL=TRUE

services:
  - xvfb
  
r_packages:
  - covr
  - smoother
  
r_binary_packages:
  - rgl

r_github_packages:
  - nategarton13/bulletcp
  - r-lib/remotes
  
install:
  - R CMD INSTALL .
  - R -e 'remotes::install_deps(dependencies = TRUE)'
  
after_success:
  - Rscript -e 'covr::codecov()'
