# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

addons:
  apt:
    update: true
    packages:
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev

env_vars:
  global:
    - RGL_USE_NULL=TRUE

services:
  - xvfb

r_binary_packages:
  - rgl
  - covr
  - assertthat
  - ggplot2
  - purrr
  - locfit
  - zoo
  - magrittr
  - dplyr
  - readr
  - tidyr
  - randomForest

r_github_packages:
  - nategarton13/bulletcp
  - heike/grooveFinder
  - heike/x3ptools

r_packages:
  - smoother

cache:
  packages: true
  directories:
    - /usr/local/lib/R/site-library
    - /usr/lib/R

after_success:
  - Rscript -e 'covr::codecov()'
