install.packages("devtools")
install.packages("roxygen2")
install.packages("x3ptools")
install.packages("randomForest")
install.packages("ggplot2")
install.packages("readr")
install.packages("dplyr")
devtools::install_github('csafe-isu/nbtrd')
devtools::install_github('bulletxtrctr')

library(devtools)
library(roxygen2)
library(dplyr)
library(bulletxtrctr)
library(x3ptools)
library(randomForest)
library(ggplot2)
library(readr)
library(nbtrd)
library(Rserve)
Rserve(port = 6311)